services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - ".env.production"
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ".env.production"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db_data:
