services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes:
      - ./api:/app


  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:

