services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes:
      - ./api:/app
      - node_modules:/app/node_modules
      - ../hls:/app/hls

  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    container_name: hypertube-frontend

volumes:
  db_data:
  node_modules:
