export default interface intraUser {
  id?: number;
  email?: string;
  login?: string;
  first_name?: string;
  last_name?: string;
  usual_full_name?: string;
  usual_first_name?: string | null;
  url?: string;
  phone?: string;
  displayname?: string;
  kind?: string;
  image?: object;
  'staff?'?: boolean;
  correction_point?: number;
  pool_month?: string;
  pool_year?: string;
  location?: string | null;
  wallet?: number;
  anonymize_date?: string;
  data_erasure_date?: string;
  created_at?: string;
  updated_at?: string;
  alumnized_at?: string | null;
  'alumni?'?: boolean;
  'active?'?: boolean;
  groups?: any[];
  cursus_users?: any[];
  projects_users?: any[];
  languages_users?: any[];
  achievements?: any[];
  titles?: any[];
  titles_users?: any[];
  partnerships?: any[];
  patroned?: any[];
  patroning?: any[];
  expertises_users?: any[];
  roles?: any[];
  campus?: any[];
  campus_users?: any[];
}
