// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Actor struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Comment struct {
	ID         int32          `json:"id"`
	Content    string         `json:"content"`
	Username   string         `json:"username"`
	UserId     int32          `json:"user_id"`
	UserAvatar sql.NullString `json:"user_avatar"`
	MovieId    int32          `json:"movie_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Director struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Genre struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Movie struct {
	ID         int32           `json:"id"`
	Title      sql.NullString  `json:"title"`
	Year       sql.NullInt32   `json:"year"`
	ImdbRating sql.NullFloat64 `json:"imdb_rating"`
	ImdbId     string          `json:"imdb_id"`
	Duration   sql.NullInt32   `json:"duration"`
	Synopsis   sql.NullString  `json:"synopsis"`
	CoverImage sql.NullString  `json:"cover_image"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}

type MovieActorsActor struct {
	MovieId int32 `json:"movie_id"`
	ActorId int32 `json:"actor_id"`
}

type MovieDirectorsDirector struct {
	MovieId    int32 `json:"movie_id"`
	DirectorId int32 `json:"director_id"`
}

type MovieGenresGenre struct {
	MovieId int32 `json:"movie_id"`
	GenreId int32 `json:"genre_id"`
}

type MovieProducersProducer struct {
	MovieId    int32 `json:"movie_id"`
	ProducerId int32 `json:"producer_id"`
}

type Producer struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type RevokedToken struct {
	ID        int32        `json:"id"`
	TokenHash string       `json:"token_hash"`
	UserId    int32        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Subtitle struct {
	ID          int32        `json:"id"`
	Language    string       `json:"language"`
	SubtitleUrl string       `json:"subtitle_url"`
	MovieId     int32        `json:"movie_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Torrent struct {
	ID         int32          `json:"id"`
	TorrentUrl string         `json:"torrent_url"`
	Quality    sql.NullString `json:"quality"`
	Size       sql.NullInt64  `json:"size"`
	MovieId    int32          `json:"movie_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type User struct {
	ID                int32          `json:"id"`
	ProfilePicture    sql.NullString `json:"profile_picture"`
	Email             string         `json:"email"`
	UserName          string         `json:"user_name"`
	LastName          string         `json:"last_name"`
	FirstName         string         `json:"first_name"`
	Password          string         `json:"password"`
	Verified          sql.NullBool   `json:"verified"`
	PreferredLanguage sql.NullString `json:"preferred_language"`
	LastActive        sql.NullTime   `json:"last_active"`
	AuthType          sql.NullString `json:"auth_type"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

type UserFavoriteMoviesMovie struct {
	UserId  int32 `json:"user_id"`
	MovieId int32 `json:"movie_id"`
}

type UserWatchedMoviesMovie struct {
	UserId  int32 `json:"user_id"`
	MovieId int32 `json:"movie_id"`
}
