// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (int32, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	DeleteComment(ctx context.Context, id int32) error
	GetCommentByID(ctx context.Context, id int32) (GetCommentByIDRow, error)
	GetComments(ctx context.Context) ([]GetCommentsRow, error)
	GetCommentsByMovieID(ctx context.Context, movieid int32) ([]GetCommentsByMovieIDRow, error)
	GetMovieByID(ctx context.Context, id int32) (GetMovieByIDRow, error)
	GetMovies(ctx context.Context) ([]GetMoviesRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
